# Generated by Django 3.2.6 on 2022-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_auto_20221015_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_number',
            field=models.CharField(default='abc', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
