# Generated by Django 3.2.6 on 2022-10-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_auto_20221015_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issued_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
