# Generated by Django 3.2.6 on 2022-10-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_alter_issue_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued_status',
            field=models.BooleanField(default=False),
        ),
    ]
