# Generated by Django 3.2.6 on 2022-10-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0005_book_issued_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='issued_status',
        ),
    ]
