# Generated by Django 3.2.6 on 2022-10-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0007_book_issued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='issued',
            new_name='issued_status',
        ),
    ]
