# Generated by Django 3.2.6 on 2022-10-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
